fix(docs):修复ch13-03 html元素结束标签缺失的问题
文章ch13-03-improving-our-io-project 59行span元素缺失结束标签导致vuepress build的时候报错：
Compiling with vite[vite:vue] Element is missing end tag.
Compiling with vite - failed in 3.10s
SyntaxError: Element is missing end tag.